### ISSUE TITLE
Write to many devices

### ISSUE THREAD

**Issue by leosmeira** [intel/bmap-tools#32]
Like this:

dc3dd hash=md5 if=image.img hof=/dev/sdb hof=/dev/sdc hof=/dev/sdd

**Comment by dedekind** [comment]
Interesting idea. I do not have time working on it though, but would find some for reviewing someone's patches. Thanks!

**Comment by lurch** [comment]
I had a quick look at this today. The command-line parsing stuff is fairly straightforward by giving the `nargs='+'` [argparse option](https://docs.python.org/3/library/argparse.html#nargs) to the [dest parameter](https://github.com/intel/bmap-tools/blob/master/bmaptools/CLI.py#L617), but the problem comes inside [copy_command](https://github.com/intel/bmap-tools/blob/master/bmaptools/CLI.py#L411). Simplifying a bit, the code basically does:
```
image_obj, dest_obj, bmap_obj, dest_is_blkdev = open_files(args)
if dest_is_blkdev:
    writer = BmapCopy.BmapBdevCopy(image_obj, dest_obj, bmap_obj)
else:
    writer = BmapCopy.BmapCopy(image_obj, dest_obj, bmap_obj)
writer.copy()
writer.sync()
```
with all the "processing" (reading the image, reading the bmap, writing the file) being done inside `writer.copy()`.

However we don't want to read the source-image multiple times when writing to multiple output files (especially as we may be downloading the source-image from a http URL, which can be quite slow), so I guess ideally things would need to be restructured so that you could do something like:
```
image_obj, dest_objs, bmap_obj, dests_are_blkdev = open_files(args)
reader = BmapReader(image_obj, bmap_obj)
writers = []
for i, dest_obj in dest_objs:
    writers.append(FileWriter(dest_obj, dests_are_blkdev[i]))
address, data_chunk = reader.read_chunk()
while data_chunk:
    for writer in writers:
        writer.write(address, data_chunk)
    address, data_chunk = reader.read_chunk()
for writer in writers:
    writer.sync()
```
I've not yet looked at the internals of BmapCopy to see how much effort this restructuring work would be though...

**Comment by dedekind** [comment]
Another idea: inside BmapCopy there is parallelism. One thread reads, the other writes. One could change this and have multiple writers.

**Comment by lurch** [comment]
I guess you'd still need to restucture it though so that there's only a single BmapCopy constructor that takes an array of `dest_objs` and an array of `dests_are_blkdev`, since the way `copy_command` currently works it wouldn't work if some dest_objs are blkdevs and others aren't.

i.e. something like:
```
image_obj, dest_objs, bmap_obj, dests_are_blkdev = open_files(args)
writer = BmapCopy.BmapMultiCopy(image_obj, dest_objs, bmap_obj, dests_are_blkdev)
writer.copy()
writer.sync()
```

**Comment by dedekind** [comment]
I guess. The arguments could be "object or a collection of objects" so that the API would not change.

**Comment by lurch** [comment]
Hmm, I think the API would _have_ to change, given that neither of the previous BmapCopy constructors accepted a `dest_is_blkdev` parameter? (which is why my previous comment introduced a hypothetical `BmapMultiCopy` class, rather than reusing any of the current BmapCopy classes :wink: )

**Comment by dedekind** [comment]
Side note: BmapCopy can find out whether something is a block device node or not. So this parameter is misnamed. Should be more along the line of "use_blkdev_optimizations". Because it is really just a set of optmizations for BmapCopy. You can use BmapCopy with block devices just fine as well.

I am not sure it was a good idea to introduce BmapBdevCopy. I do not remember the motivation. It could have been just an optional argument of BmapCopy. And it can be changed this way. This was my first python project, and I think I'd go for an optional argument nowadays.

I am not sure the 3rd class is needed. I'd start with modifying BmapCopy to support multiple output files, and went for a separate class only if there were strong reasons for that.

**Comment by dedekind** [comment]
I do not think I have time to work on this. If someone is enthusiastic enough, pull requests are welcome.

**Comment by dedekind** [comment]
Hello, the project was moved and now owned by a new team. Please, work with them. Check the README.md file. Thanks!

**Comment by dedekind** [comment]
@lurch hi, may be @twoerner can comment, I believe he is the new maintainer, correct @twoerner ?
